### ISSUE TITLE
get_genomic_distance_map.py works only with "barcode_" format

### ISSUE THREAD

**Issue by MarionBardou** [pyHi-M/pyHiM_tools#1]
I tried to run get_genomic_distance_map.py on my ecsv and bed files, and I get the following error :

```
(pyHiM_refact) bardou@darwin:/mnt/grey/DATA/users/Marion/Hi-M_analysis_Droso_brain/rut/OK107/no_projection/Combined_traces/OK107/rep_1/Norm_by_gen_dist$ get_genomic_distance_map.py --barcodes_file_path Trace_combined_3D_method:mask_label:OK107_action:labeled_Matrix_uniqueBarcodes.ecsv --bed_file_path Library_Summary_rut_4RT.bed
$ input parameters: input 
barcodes file: Trace_combined_3D_method:mask_label:OK107_action:labeled_Matrix_uniqueBarcodes.ecsv
BED file: Library_Summary_rut_4RT.bed
Traceback (most recent call last):
  File "/home/bardou/Repositories/pyHiM_tools/tools/get_genomic_distance_map.py", line 137, in <module>
    main()       
  File "/home/bardou/Repositories/pyHiM_tools/tools/get_genomic_distance_map.py", line 127, in main
    run_process(barcodes_file_path=barcodes_file_path,
  File "/home/bardou/Repositories/pyHiM_tools/tools/get_genomic_distance_map.py", line 92, in run_process
    start_seq = int(barcode_dict[barcode_str][0]['start'])
KeyError: 'barcode_1'
```

I think it is because the code searches for the format "barcode_" while my barcodes are named in the following manner :

revmer1
revcompmer2
revmer3
revmer7
revmer8
revmer9
revmer10
revmer11
revmer12
revmer13
revmer14
revmer15
revmer16
revmer17
revmer18
revmer19
revmer20
revmer21
revmer23
revmer24
revmer26
revmer27
revmer28
rs0639ss
rs0708ss

Could it be possible to change the code to make it more flexible to other barcodes format ?

**Comment by marcnol** [comment]
you need to rename the barcodes otherwise it will not work I think. I will look into the code but do not know how easy it will be to change

**Comment by marcnol** [comment]
I did a change of the script... but writing a robust script to correlate the names in the uniquebarcode file with the somehow random nomenclatures in the bed file will be impossible...

thus we now impose that the names in the uniquebarcodes file HAVE TO BE the same as in the bed file. So only numbers are allowed.
